### PR TITLE
Fix MalwarePatrol free DB download

### PR DESCRIPTION
**Pull request by mizzy241**
Free product code changed from 8 to 32 according to MalwarePatrol docs:

"Use 32 if you have a Free Guard account, 34 for Basic Defense monthly, 33 for Basic Defense yearly,
and 37 for Basic Defense EDU/Contributor (Free) accounts."

### CODE REVIEW

**Comment by perplexityjeff** [comment]
Nice change seems good, I checked in my source as well and made the changes. Maybe an idea to also change the master.conf in the source to 32 instead of 8 and add it to this pull. 

I myself fixed this some time ago with a user.conf change by adding line `malwarepatrol_product_code="32"` but making the change in the code is of course much better. 

Reference from the documentation @mizzy241 mentioned: https://www.malwarepatrol.net/tech-support/

**Comment by mizzy241** [comment]
Yes, you definitely right about corresponding changes in config files. Pull updated.

**Comment by perplexityjeff** [comment]
Looking great, let's hope that it gets added :D.

**Review by extremeshok — APPROVED** [review]

**Comment by kovacs-andras** [comment]
Thanks! I just ran into the same issue. The Malware Patrol blog and tech-support guides are disambigous. I hope this fix will be merged into the master once.

**Pull request merged**
