### PR TITLE
Remove database files after disabling a database group

### PR DESCRIPTION
**Pull request by reneschuster**

### CODE REVIEW

**Comment by extremeshok** [comment]
Test Build fails with
````
clamav-unofficial-sigs.sh: line 1444: syntax error near unexpected token `else'
clamav-unofficial-sigs.sh: line 1444: `else'
.. ERROR
````

**Comment by reneschuster** [comment]
I have tested it on my system and all was working fine. But I'll check again later on.

**Comment by reneschuster** [comment]
For your information, I haven't checked it again. Didn't had time.

**Comment by extremeshok** [comment]
I know, busy bug fixing the commit.

__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by extremeshok** [comment]
Fixed in latest commit to dev :_P

__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by reneschuster** [comment]
OK, thanks.

**Pull request merged**
