### PR TITLE
5.1.0

### PR DESCRIPTION
**Pull request by extremeshok**
- eXtremeSHOK.com Maintenance 
 - Added --install-cron this will automatically generate and install the cron file
 - Added --install-logrotate this will automatically generate and install the logrotate file
 - Change official URL of SecuriteInfo signatures
 - Added a new database (securiteinfoandroid.hdb) for SecuriteInfo 
 - Remove database files after disabling a database group by @reneschuster
 - Updated Gentoo OS config by @orlitzky
 - Regroup functiuons
 - Increase travis-ci code testing
 - Set minimum config required to 60
 - Bump config to 60

### CODE REVIEW

**Comment by orlitzky** [comment]
I'm skeptical about 7bcf856 without a corresponding config flag... just because I don't want updates right now doesn't mean I want to delete all of the signatures that I already have installed. I think you might surprise some people who expect that disabling the updates will do only that.

**Comment by extremeshok** [comment]
@orlitzky i will add a config option, default too keep ?

**Comment by reneschuster** [comment]
The option *sanesecurity_enabled=yes** would mean I want to **enable** the Sanesecurity Rules. When I do not want them anymore, I'll change to **no** and then I would also asume that the Rules are disabled and removed. Nothing mentioning here that only updates will be disabled.

My proposal is to make an additional option with **sanesecurity_updates=yes**. It's the much better approach.

**Comment by extremeshok** [comment]
Was thinking more along the lines of using a "remove_disabled_databases" option

**Comment by reneschuster** [comment]
Too complicated and error prone.

**_enabled=no** is alwasy I do not want to use something, so it should not be anabled by default in clamav. That has nothing to do with updates at all.

An option for enabling and disabling updates is much better.

**Comment by orlitzky** [comment]
Something like `remove_disabled_databases` is what I was thinking. I'll know better anyway since I happened to see the commit message, but I think otherwise you're going to surprise people. 

The **_enabled=no** thing is a matter of context. If you had that set in clamd.conf, I would agree with you. But it's not -- it's part of the config file for a tool that has only performed _updates_ for 7 years. In that context, setting **_enabled=no** means "no updates" to me. Or even stronger, "do nothing regarding these databases."

**Comment by extremeshok** [comment]
will push a small patch once ive moved back in my new office.

**Comment by smwardle** [comment]
https://github.com/extremeshok/clamav-unofficial-sigs says:
"ClamAV Unofficial Signatures Updater"
Nothing about removing databases that are not enabled.
Changing default behaviour with no warning is bad.

**Comment by extremeshok** [comment]
to a few of us it made sense ;-P

Busy with the fix, wont be long

**Comment by smwardle** [comment]
Thanks. Opened this as a bug on ticket #88 from work earlier today before seeing this discussion.

**Comment by extremeshok** [comment]
Commit fe6b0b8250ca61110a552016be31e8955f2a0cb2  will fix thisx, please test with the latest dev 

Added the config option remove_disabled_databases # Default is "no", if enabled when a database is disabled we will remove the associated database files.

**Comment by smwardle** [comment]
Tested and works as documented with both remove_disabled_databases="yes" and remove_disabled_databases="no".
Thanks.

**Pull request merged**
